import ManagerTemplate from "@/components/managerTemplate"
import MenuList from "../menuList"
export const metadata = {
 title: 'AboutUs | MounRent',
 description: 'Generated by create next app',
}
type PropsLayout = {
 children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
 return (
 <ManagerTemplate title="AboutUs" id="AboutUs"
menuList={MenuList}>
 {children}
 </ManagerTemplate>
 )
}
export default RootLayout