import { BASE_API_URL } from "@/global"
import { storeCookie } from "../lib/client-cookie"
import axios from "axios"
import Image from "next/image"
import { useRouter } from "next/router"
import { FormEvent,useState } from "react"
import { ToastContainer, toast } from "react-toastify"



export const metadata = { 
    title: 'Login | MountRent', 
    description: 'Generated by create next app', 
} 

type PropsLayout = { 
    children: React.ReactNode 
} 

const loginLayout = ({ children }: PropsLayout) => {

    return (
        <div className="flex h-screen">
            {/* Left side with background image */}
            <div className="hidden md:block w-1/2 h-full relative ">
                <img src="bg-login" alt="Mountain" className="w-full h-full object-cover"/>
            </div>

            {/* Right side with the sign-up form */}
            <div className="w-full md:w-1/2 flex items-center justify-center bg-gray-50">
                <div className="w-full max-w-md px-8 py-10 bg-white shadow-md rounded-lg">
                    <div className="flex justify-center mb-8">
                        {/* Logo */}
                        <div className="flex items-center space-x-2">
                            <div className="bg-orange-500 w-10 h-10 rounded-full flex items-center justify-center">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 10h11m4 0h4M3 14h15m4 0h-4m-2 4h4M5 6h16a2 2 0 012 2v4a2 2 0 01-2 2H3a2 2 0 01-2-2V8a2 2 0 012-2z" />
                                </svg>
                            </div>
                            <span className="text-orange-500 font-bold text-2xl">MOUNRENT</span>
                        </div>
                    </div>

                    <h2 className="text-center text-2xl font-bold text-gray-700 mb-6">LOGIN</h2>

                    {/* Form */}
                    <form action="#" method="POST">
                        <div className="mb-4">
                            <label htmlFor="username" className="block text-sm font-medium text-gray-600">Username or Email</label>
                            <input type="text" id="username" name="username" className="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-orange-500 focus:outline-none" />
                        </div>

                        <div className="mb-4">
                            <label htmlFor="password" className="block text-sm font-medium text-gray-600">Password</label>
                            <input type="password" id="password" name="password" className="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-orange-500 focus:outline-none" />
                            <a href="#" className="text-sm text-orange-500 hover:underline mt-2 inline-block">Lupa password?</a>
                        </div>

                        <button type="submit" className="w-full bg-orange-500 text-white py-2 rounded-md text-lg font-semibold hover:bg-orange-600">LOGIN</button>
                    </form>

                    <div className="text-center my-6 text-sm text-gray-500">Or Sign Up with Google</div>

                    <button className="w-full flex items-center justify-center border border-gray-300 py-2 rounded-md hover:bg-gray-100">
                        <img src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="Google Logo" className="h-6 w-6 mr-2" />
                        Google Account
                    </button>
                </div>
            </div>
        </div>
    );
};

export default loginLayout;