import ManagerTemplate from "@/components/managerTemplate"
import MenuList from "../menuList"
export const metadata = {
 title: 'GRWM | MountRent',
 description: 'Generated by create next app',
}
type PropsLayout = {
 children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
 return (
 <ManagerTemplate title="GRWM" id="GRWM"
menuList={MenuList}>
 {children}
 </ManagerTemplate>
 )
}
export default RootLayout